/*
 * PALEO: Petite Application Logicielle d'Etude Objet
 *
 * <p>PALEO est un pseudo-compilateur generant des schemas memoires en fonction d'instructions Java.</p>
 * 
 * Projet de Synthese (LCIN4U51)
 * Licence Informatique Semestre 4
 * Universite Henri Poincare (UHP Nancy)
 * 
 * @author: Jan KEROMNES
 * @version: 1.0
 * 
 */
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 19 09:45:49 CEST 2010
//----------------------------------------------------

package paleo.analyse;

// TODO: Auto-generated Javadoc
/**
 * Les Codes Lexicaux.
 */
public class CodesLexicaux {
	/* terminals */
	/** The Constant IDF. */
	public static final int IDF = 7;
	
	/** The Constant POINTVIRGULE. */
	public static final int POINTVIRGULE = 2;
	
	/** The Constant NULL. */
	public static final int NULL = 4;
	
	/** The Constant EOF. */
	public static final int EOF = 0;
	
	/** The Constant TYPEPRIMITIF. */
	public static final int TYPEPRIMITIF = 6;
	
	/** The Constant EGAL. */
	public static final int EGAL = 3;
	
	/** The Constant POINT. */
	public static final int POINT = 5;
	
	/** The Constant error. */
	public static final int error = 1;
	
	/** The Constant EXPR. */
	public static final int EXPR = 8;
	
	/** The Constant CLASSE. */
	public static final int CLASSE = 9;
}
